/* Load this script using conditional IE comments if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icomoon\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-byui-logo' : '&#xe000;',
			'icon-lds-church' : '&#xe001;',
			'icon-vcard' : '&#xe002;',
			'icon-export' : '&#xe003;',
			'icon-graduation' : '&#xe005;',
			'icon-book' : '&#xe006;',
			'icon-megaphone' : '&#xe007;',
			'icon-briefcase' : '&#xe009;',
			'icon-pictures' : '&#xe00b;',
			'icon-install' : '&#xe00c;',
			'icon-book-2' : '&#xe00d;',
			'icon-triangle-left' : '&#xe00e;',
			'icon-triangle-down' : '&#xe00f;',
			'icon-triangle-up' : '&#xe010;',
			'icon-triangle-right' : '&#xe011;',
			'icon-angle-left' : '&#xe012;',
			'icon-angle-down' : '&#xe013;',
			'icon-angle-up' : '&#xe014;',
			'icon-angle-right' : '&#xe015;',
			'icon-home' : '&#xe01a;',
			'icon-office' : '&#xe01b;',
			'icon-phone' : '&#xe01c;',
			'icon-address-book' : '&#xe01d;',
			'icon-keyboard' : '&#xe01f;',
			'icon-radio-unchecked' : '&#xe022;',
			'icon-radio-checked' : '&#xe023;',
			'icon-flashlight' : '&#xe025;',
			'icon-play' : '&#xe02f;',
			'icon-pushpin' : '&#xe030;',
			'icon-chat-alt-stroke' : '&#xe008;',
			'icon-chat-alt-fill' : '&#xe00a;',
			'icon-checkmark' : '&#xe021;',
			'icon-check-alt' : '&#xe024;',
			'icon-x' : '&#xe026;',
			'icon-x-altx-alt' : '&#xe027;',
			'icon-denied' : '&#xe028;',
			'icon-cursor' : '&#xe029;',
			'icon-rss' : '&#xe02a;',
			'icon-rss-alt' : '&#xe02b;',
			'icon-wrench' : '&#xe02c;',
			'icon-dial' : '&#xe02d;',
			'icon-cog' : '&#xe02e;',
			'icon-calendar-alt-stroke' : '&#xe032;',
			'icon-calendar-alt-fill' : '&#xe033;',
			'icon-share' : '&#xe034;',
			'icon-mail' : '&#xe035;',
			'icon-heart-stroke' : '&#xe036;',
			'icon-heart-fill' : '&#xe037;',
			'icon-movie' : '&#xe038;',
			'icon-document-alt-stroke' : '&#xe039;',
			'icon-document-alt-fill' : '&#xe03a;',
			'icon-document-stroke' : '&#xe03b;',
			'icon-document-fill' : '&#xe03c;',
			'icon-plus' : '&#xe03d;',
			'icon-plus-alt' : '&#xe03e;',
			'icon-minus' : '&#xe03f;',
			'icon-minus-alt' : '&#xe040;',
			'icon-pin' : '&#xe041;',
			'icon-link' : '&#xe042;',
			'icon-bolt' : '&#xe043;',
			'icon-move-alt2' : '&#xe046;',
			'icon-award-fill' : '&#xe048;',
			'icon-award-stroke' : '&#xe049;',
			'icon-magnifying-glass' : '&#xe04a;',
			'icon-key-stroke' : '&#xe04f;',
			'icon-key-fill' : '&#xe050;',
			'icon-new-window' : '&#xe051;',
			'icon-lightbulb' : '&#xe052;',
			'icon-spin-alt' : '&#xe053;',
			'icon-curved-arrow' : '&#xe055;',
			'icon-undo' : '&#xe056;',
			'icon-reload' : '&#xe057;',
			'icon-loop' : '&#xe059;',
			'icon-arrow-left' : '&#xe065;',
			'icon-arrow-left-alt1' : '&#xe066;',
			'icon-arrow-right' : '&#xe068;',
			'icon-arrow-right-alt1' : '&#xe069;',
			'icon-arrow-up' : '&#xe06b;',
			'icon-arrow-up-alt1' : '&#xe06c;',
			'icon-arrow-down' : '&#xe06e;',
			'icon-arrow-down-alt1' : '&#xe06f;',
			'icon-steering-wheel' : '&#xe072;',
			'icon-microphone' : '&#xe073;',
			'icon-headphones' : '&#xe074;',
			'icon-volume' : '&#xe075;',
			'icon-volume-mute' : '&#xe076;',
			'icon-play-2' : '&#xe077;',
			'icon-pause' : '&#xe078;',
			'icon-stop' : '&#xe079;',
			'icon-first' : '&#xe07b;',
			'icon-last' : '&#xe07c;',
			'icon-play-alt' : '&#xe07d;',
			'icon-fullscreen-exit' : '&#xe07e;',
			'icon-fullscreen-exit-alt' : '&#xe07f;',
			'icon-fullscreen' : '&#xe080;',
			'icon-fullscreen-alt' : '&#xe081;',
			'icon-iphone' : '&#xe082;',
			'icon-compass' : '&#xe087;',
			'icon-box' : '&#xe088;',
			'icon-folder-stroke' : '&#xe089;',
			'icon-folder-fill' : '&#xe08a;',
			'icon-at' : '&#xe08b;',
			'icon-ampersand' : '&#xe08c;',
			'icon-info' : '&#xe08d;',
			'icon-question-mark' : '&#xe08e;',
			'icon-pilcrow' : '&#xe08f;',
			'icon-hash' : '&#xe090;',
			'icon-left-quote' : '&#xe091;',
			'icon-right-quote' : '&#xe092;',
			'icon-read-more' : '&#xe096;',
			'icon-list' : '&#xe097;',
			'icon-book-3' : '&#xe099;',
			'icon-book-alt' : '&#xe09a;',
			'icon-book-alt2' : '&#xe09b;',
			'icon-pen' : '&#xe09c;',
			'icon-brush' : '&#xe0a0;',
			'icon-layers-alt' : '&#xe0a3;',
			'icon-layers' : '&#xe0a4;',
			'icon-image' : '&#xe0a5;',
			'icon-camera' : '&#xe0a6;',
			'icon-chart' : '&#xe0a9;',
			'icon-chart-alt' : '&#xe0aa;',
			'icon-eye' : '&#xe0ad;',
			'icon-user' : '&#xe0ae;',
			'icon-home-2' : '&#xe0af;',
			'icon-clock' : '&#xe0b0;',
			'icon-tag-stroke' : '&#xe0b5;',
			'icon-tag-fill' : '&#xe0b6;',
			'icon-star' : '&#xe0be;',
			'icon-map-pin-fill' : '&#xe0c0;',
			'icon-download' : '&#xe0c3;',
			'icon-upload' : '&#xe0c4;',
			'icon-cloud-download' : '&#xe0c5;',
			'icon-cloud-upload' : '&#xe0c6;',
			'icon-fork' : '&#xe0c7;',
			'icon-paperclip' : '&#xe0c8;',
			'icon-trash-fill' : '&#xe04c;',
			'icon-trash-stroke' : '&#xe04b;',
			'icon-eject' : '&#xe07a;',
			'icon-article' : '&#xe095;',
			'icon-list-nested' : '&#xe098;',
			'icon-pen-alt-fill' : '&#xe09e;',
			'icon-eyedropper' : '&#xe0a2;',
			'icon-lock-stroke' : '&#xe0b1;',
			'icon-lock-fill' : '&#xe0b2;',
			'icon-unlock-stroke' : '&#xe0b3;',
			'icon-unlock-fill' : '&#xe0b4;',
			'icon-file-pdf' : '&#xe004;',
			'icon-file-word' : '&#xe016;',
			'icon-file-excel' : '&#xe017;',
			'icon-facebook' : '&#xe018;',
			'icon-twitter' : '&#xe019;',
			'icon-feed' : '&#xe01e;',
			'icon-youtube' : '&#xe020;',
			'icon-linkedin' : '&#xe031;',
			'icon-file-zip' : '&#xe044;',
			'icon-libreoffice' : '&#xe045;',
			'icon-books' : '&#xe047;',
			'icon-library' : '&#xe04d;',
			'icon-bell' : '&#xe04e;',
			'icon-map' : '&#xe054;',
			'icon-map-2' : '&#xe058;',
			'icon-food' : '&#xe05a;',
			'icon-spinner' : '&#xe05b;',
			'icon-spinner-2' : '&#xe05c;',
			'icon-clipboard' : '&#xe05d;',
			'icon-code' : '&#xe05e;',
			'icon-earth' : '&#xe05f;',
			'icon-suitcase' : '&#xe060;',
			'icon-chat' : '&#xe061;',
			'icon-camera-2' : '&#xe062;',
			'icon-calendar' : '&#xe063;',
			'icon-bell-2' : '&#xe064;',
			'icon-link-2' : '&#xe067;',
			'icon-search' : '&#xe06a;',
			'icon-popup' : '&#xe06d;',
			'icon-network' : '&#xe070;',
			'icon-upload-2' : '&#xe071;',
			'icon-download-2' : '&#xe083;',
			'icon-install-2' : '&#xe084;',
			'icon-cloud' : '&#xe085;',
			'icon-upload-3' : '&#xe086;',
			'icon-archive' : '&#xe093;',
			'icon-bookmark' : '&#xe094;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};